### ISSUE TITLE
Request for markdown package

### ISSUE THREAD

**Issue by jgordon** [tectonic-typesetting/tectonic-staging#6] opened 2018-05-01 23:51 UTC
I'm interested in using the [markdown package](https://ctan.org/pkg/markdown) with tectonic. 

Putting the markdown.sty file in the current directory results in an error, that the `\markdown` command is previously defined, so there may be additional complications making it work with tectonic. 

Thanks!

**Comment by pkgw** [comment] 2018-05-07 13:45
Thanks for the request! I'm overdue to update the standard bundle so I'll look into this. Do you happen to have a sample document demonstrating its usage? I'm sure I can come up with one if that's not convenient for you, though.

**Comment by jgordon** [comment] 2018-05-08 18:06
Here's a [basic example](https://github.com/tectonic-typesetting/tectonic-staging/files/1985101/markdown-ex.txt). It works using XeTeX (tested on Overleaf).

With Tectonic, putting markdown.sty (built with XeTeX from the package linked above) in the current directory, I get this error:

```
(markdown-ex.txt
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(size10.clo)) (markdown.sty (keyval.sty) (url.sty) (graphicx.sty (graphics.sty
(trig.sty) (graphics.cfg) (xetex.def (infwarerr.sty) (ltxcmds.sty))))
(ifthen.sty) (fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz)) (csvsimple.sty (pgfkeys.sty (pgfkeys.code.tex
(pgfkeysfiltered.code.tex)))) (markdown

! LaTeX Error: Command \markdown already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.55 \newenvironment{markdown}\relax\relax
                                          
No pages of output.
Transcript written on markdown-ex.log.
```

**Comment by pkgw** [comment] 2018-09-18 18:05
Well, I've got good news and bad news. I'm finally working deploying an updated version of the default bundle, and it should now include the markdown package. It can be tested if you install Tectonic version >=0.1.9 and run it with the following `-w` argument:

```
tectonic -w https://newton.cx/~peter/files/tlextras-2018.1dev.tar mydoc.tex
```

The bad news is that it seems that the Markdown package requires Unix shell access, and that is disabled in Tectonic. So unfortunately the demo you linked above still doesn't work. I kind of want to disable shell access by default since it breaks reproducible document builds, but I am definitely open to adding it as an optional feature.

**Comment by jgordon** [comment] 2018-09-18 18:18
Thank you for looking into this, and I can certainly understand that policy!

**Comment by pkgw** [comment] 2018-09-18 18:46
OK. I'll close this since this component of the issue is "solved" from the standpoint of this repository. [tectonic #38](https://github.com/tectonic-typesetting/tectonic/issues/38) regards support for shell escaping.

**Comment by pkgw** [comment] 2020-10-10 21:55
Never actually closed this one.

**Closed by pkgw** 2020-10-10 21:55 UTC

**Comment by mnrvwl** [comment] 2023-04-08 11:33
@pkgw I've been using the `markdown` package lately, and I wonder whether we consider reopening this. As of now it's not working with `tectonic`.

The package depends on a `texlua` call in combination with `shell-escape` to work properly, but using XeTeX works without issue:
```console
$ latexmk -pdfxe -outdir=. -shell-escape test.tex
```

With `tectonic` it fails, even if now we can shell escape it:
```
$ tectonic -Z shell-escape test.tex
Running TeX ...
note: running shell command: `texlua "./test.markdown.lua" > "./test.markdown.out"`
error: ./_markdown_test/34540d5a4687ec4a6207a8d5db357c8e.md.tex:2: Undefined control sequence
error: halted on potentially-recoverable error as specified
```

Note that in the [docs](https://osl.ugr.es/CTAN/macros/generic/markdown/markdown.pdf), redefining `\markdownOptionOutputDir` may be necessary to match the output directory when it's a different value than the default.

MWE `test.tex`:
```latex
\documentclass{article}
  \usepackage{markdown}

\begin{document}
\begin{markdown}
# Grocery list
*Remember* to grab as much as we can during upcoming [sales](http://acme-marg.com)!

## Food
- baked beans
- spaghetti

## Stationery
- writing pad
- pencils
\end{markdown}
\end{document}
```
